baseURL = 'https://sy1.sh/'
languageCode = 'en-us'
title = 'sy1's blog'
theme = 'hugo-dead-simple'

[menu]
  [[menu.main]]
    name = "<u>H</u>ome"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "<u>A</u>bout"
    url = "/about"
    weight = 2

  [[menu.main]]
    name = "<u>W</u>riteups"
    url = "/writeups"
    weight = 2